In [1]:
import pandas as pd
import numpy as np

print("success")

success

In [2]:
df = pd.read_csv(
    "https://raw.githubusercontent.com/pandas-dev/pandas/main/doc/data/titanic.csv"
)

df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [4]:
print(df.shape)

print(df.columns)

(891, 12)
Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [6]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [7]:
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

Explanation:

The shape shows the number of rows and columns in the dataset.

The describe() function provides summary statistics for numerical columns.

In [9]:
df["Name"]

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                  Heikkinen, Miss Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                          Graham, Miss Margaret Edith
888              Johnston, Miss Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [10]:
df[["Name", "Age", "Fare"]]

                                                  Name   Age     Fare
0                              Braund, Mr. Owen Harris  22.0   7.2500
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0  71.2833
2                                Heikkinen, Miss Laina  26.0   7.9250
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0  53.1000
4                             Allen, Mr. William Henry  35.0   8.0500
..                                                 ...   ...      ...
886                              Montvila, Rev. Juozas  27.0  13.0000
887                        Graham, Miss Margaret Edith  19.0  30.0000
888            Johnston, Miss Catherine Helen "Carrie"   NaN  23.4500
889                              Behr, Mr. Karl Howell  26.0  30.0000
890                                Dooley, Mr. Patrick  32.0   7.7500

[891 rows x 3 columns]

In [11]:
df[df["Age"] > 60]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
33,34,0,2,"Wheadon, Mr. Edward H",male,66.0,0,0,C.A. 24579,10.5000,NaN,S
54,55,0,1,"Ostby, Mr. Engelhart Cornelius",male,65.0,0,1,113509,61.9792,B30,C
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
170,171,0,1,"Van der hoef, Mr. Wyckoff",male,61.0,0,0,111240,33.5000,B19,S
252,253,0,1,"Stead, Mr. William Thomas",male,62.0,0,0,113514,26.5500,C87,S
275,276,1,1,"Andrews, Miss Kornelia Theodosia",female,63.0,1,0,13502,77.9583,D7,S
280,281,0,3,"Duane, Mr. Frank",male,65.0,0,0,336439,7.7500,NaN,Q
326,327,0,3,"Nysveen, Mr. Johan Hansen",male,61.0,0,0,345364,6.2375,NaN,S
438,439,0,1,"Fortune, Mr. Mark",male,64.0,1,4,19950,263.0000,C23 C25 C27,S
456,457,0,1,"Millet, Mr. Francis Davis",male,65.0,0,0,13509,26.5500,E38,S
483,484,1,3,"Turkula, Mrs. (Hedwig)",female,63.0,0,0,4134,9.5875,NaN,S
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C
545,546,0,1,"Nicholson, Mr. Arthur Ernest",male,64.0,0,0,693,26.0000,NaN,S
555,556,0,1,"Wright, Mr. George",male,62.0,0,0,113807,26.5500,NaN,S
570,571,1,2,"Harris, Mr. George",male,62.0,0,0,S.W./PP 752,10.5000,NaN,S
625,626,0,1,"Sutton, Mr. Frederick",male,61.0,0,0,36963,32.3208,D50,S
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S
672,673,0,2,"Mitchell, Mr. Henry Michael",male,70.0,0,0,C.A. 24580,10.5000,NaN,S
745,746,0,1,"Crosby, Capt. Edward Gifford",male,70.0,1,1,WE/P 5735,71.0000,B22,S
829,830,1,1,"Stone, Mrs. George Nelson (Martha Evelyn)",female,62.0,0,0,113572,80.0000,B28,NaN
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S

In [12]:
df[(df["Fare"] > 100) & (df["Pclass"] == 1)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.00,3,2,19950,263.0000,C23 C25 C27,S
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C
88,89,1,1,"Fortune, Miss Mabel Helen",female,23.00,3,2,19950,263.0000,C23 C25 C27,S
118,119,0,1,"Baxter, Mr. Quigg Edmond",male,24.00,0,1,PC 17558,247.5208,B58 B60,C
195,196,1,1,"Lurette, Miss Elise",female,58.00,0,0,PC 17569,146.5208,B80,C
215,216,1,1,"Newell, Miss Madeleine",female,31.00,1,0,35273,113.2750,D36,C
258,259,1,1,"Ward, Miss Anna",female,35.00,0,0,PC 17755,512.3292,NaN,C
268,269,1,1,"Graham, Mrs. William Thompson (Edith Junkins)",female,58.00,0,1,PC 17582,153.4625,C125,S
269,270,1,1,"Bissette, Miss Amelia",female,35.00,0,0,PC 17760,135.6333,C99,S
297,298,0,1,"Allison, Miss Helen Loraine",female,2.00,1,2,113781,151.5500,C22 C26,S
299,300,1,1,"Baxter, Mrs. James (Helene DeLaudeniere Chaput)",female,50.00,0,1,PC 17558,247.5208,B58 B60,C
305,306,1,1,"Allison, Master Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S
306,307,1,1,"Fleming, Miss Margaret",female,NaN,0,0,17421,110.8833,NaN,C
307,308,1,1,"Penasco y Castellana, Mrs. Victor de Satode (M...",female,17.00,1,0,PC 17758,108.9000,C65,C
311,312,1,1,"Ryerson, Miss Emily Borie",female,18.00,2,2,PC 17608,262.3750,B57 B59 B63 B66,C
318,319,1,1,"Wick, Miss Mary Natalie",female,31.00,0,2,36928,164.8667,C7,S
319,320,1,1,"Spedden, Mrs. Frederic Oakley (Margaretta Corn...",female,40.00,1,1,16966,134.5000,E34,C
325,326,1,1,"Young, Miss Marie Grice",female,36.00,0,0,PC 17760,135.6333,C32,C
332,333,0,1,"Graham, Mr. George Edward",male,38.00,0,1,PC 17582,153.4625,C91,S
334,335,1,1,"Frauenthal, Mrs. Henry William (Clara Heinshei...",female,NaN,1,0,PC 17611,133.6500,NaN,S
337,338,1,1,"Burns, Miss Elizabeth Margaret",female,41.00,0,0,16966,134.5000,E40,C
341,342,1,1,"Fortune, Miss Alice Elizabeth",female,24.00,3,2,19950,263.0000,C23 C25 C27,S
373,374,0,1,"Ringhini, Mr. Sante",male,22.00,0,0,PC 17760,135.6333,NaN,C
377,378,0,1,"Widener, Mr. Harry Elkins",male,27.00,0,2,113503,211.5000,C82,C
380,381,1,1,"Bidois, Miss Rosalie",female,42.00,0,0,PC 17757,227.5250,NaN,C
390,391,1,1,"Carter, Mr. William Ernest",male,36.00,1,2,113760,120.0000,B96 B98,S
393,394,1,1,"Newell, Miss Marjorie",female,23.00,1,0,35273,113.2750,D36,C
435,436,1,1,"Carter, Miss Lucile Polk",female,14.00,1,2,113760,120.0000,B96 B98,S
438,439,0,1,"Fortune, Mr. Mark",male,64.00,1,4,19950,263.0000,C23 C25 C27,S
498,499,0,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.00,1,2,113781,151.5500,C22 C26,S
505,506,0,1,"Penasco y Castellana, Mr. Victor de Satode",male,18.00,1,0,PC 17758,108.9000,C65,C
527,528,0,1,"Farthing, Mr. John",male,NaN,0,0,PC 17483,221.7792,C95,S
537,538,1,1,"LeRoy, Miss Bertha",female,30.00,0,0,PC 17761,106.4250,NaN,C
544,545,0,1,"Douglas, Mr. Walter Donald",male,50.00,1,0,PC 17761,106.4250,C86,C
550,551,1,1,"Thayer, Mr. John Borland Jr",male,17.00,0,2,17421,110.8833,C70,C
557,558,0,1,"Robbins, Mr. Victor",male,NaN,0,0,PC 17757,227.5250,NaN,C
581,582,1,1,"Thayer, Mrs. John Borland (Marian Longstreth M...",female,39.00,1,1,17421,110.8833,C68,C
609,610,1,1,"Shutes, Miss Elizabeth W",female,40.00,0,0,PC 17582,153.4625,C125,S
659,660,0,1,"Newell, Mr. Arthur Webster",male,58.00,0,2,35273,113.2750,D48,C
660,661,1,1,"Frauenthal, Dr. Henry William",male,50.00,2,0,PC 17611,133.6500,NaN,S
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.00,0,1,PC 17755,512.3292,B51 B53 B55,C
689,690,1,1,"Madill, Miss Georgette Alexandra",female,15.00,0,1,24160,211.3375,B5,S
698,699,0,1,"Thayer, Mr. John Borland",male,49.00,1,1,17421,110.8833,C68,C
700,701,1,1,"Astor, Mrs. John Jacob (Madeleine Talmadge Force)",female,18.00,1,0,PC 17757,227.5250,C62 C64,C
708,709,1,1,"Cleaver, Miss Alice",female,22.00,0,0,113781,151.5500,NaN,S
716,717,1,1,"Endres, Miss Caroline Louise",female,38.00,0,0,PC 17757,227.5250,C45,C
730,731,1,1,"Allen, Miss Elisabeth Walton",female,29.00,0,0,24160,211.3375,B5,S
737,738,1,1,"Lesurer, Mr. Gustave J",male,35.00,0,0,PC 17755,512.3292,B101,C
742,743,1,1,"Ryerson, Miss Susan Parker ""Suzette""",female,21.00,2,2,PC 17608,262.3750,B57 B59 B63 B66,C
763,764,1,1,"Carter, Mrs. William Ernest (Lucile Polk)",female,36.00,1,2,113760,120.0000,B96 B98,S
779,780,1,1,"Robert, Mrs. Edward Scott (Elisabeth Walton Mc...",female,43.00,0,1,24160,211.3375,B3,S
802,803,1,1,"Carter, Master William Thornton II",male,11.00,1,2,113760,120.0000,B96 B98,S
856,857,1,1,"Wick, Mrs. George Dennick (Mary Hitchcock)",female,45.00,1,1,36928,164.8667,NaN,S

In [13]:
df[["Name", "Age", "Fare"]]

                                                  Name   Age     Fare
0                              Braund, Mr. Owen Harris  22.0   7.2500
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0  71.2833
2                                Heikkinen, Miss Laina  26.0   7.9250
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0  53.1000
4                             Allen, Mr. William Henry  35.0   8.0500
..                                                 ...   ...      ...
886                              Montvila, Rev. Juozas  27.0  13.0000
887                        Graham, Miss Margaret Edith  19.0  30.0000
888            Johnston, Miss Catherine Helen "Carrie"   NaN  23.4500
889                              Behr, Mr. Karl Howell  26.0  30.0000
890                                Dooley, Mr. Patrick  32.0   7.7500

[891 rows x 3 columns]

In [14]:
df.iloc[0]

PassengerId                          1
Survived                             0
Pclass                               3
Name           Braund, Mr. Owen Harris
Sex                               male
Age                               22.0
SibSp                                1
Parch                                0
Ticket                       A/5 21171
Fare                              7.25
Cabin                              NaN
Embarked                             S
Name: 0, dtype: object

In [15]:
df.iloc[0:5, 0:3]

   PassengerId  Survived  Pclass
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

Explanation:

iloc[] is used to select rows and columns by position.

Double brackets are used when selecting multiple columns.

In [16]:
df[df["Age"] > 60]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
33,34,0,2,"Wheadon, Mr. Edward H",male,66.0,0,0,C.A. 24579,10.5000,NaN,S
54,55,0,1,"Ostby, Mr. Engelhart Cornelius",male,65.0,0,1,113509,61.9792,B30,C
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
170,171,0,1,"Van der hoef, Mr. Wyckoff",male,61.0,0,0,111240,33.5000,B19,S
252,253,0,1,"Stead, Mr. William Thomas",male,62.0,0,0,113514,26.5500,C87,S
275,276,1,1,"Andrews, Miss Kornelia Theodosia",female,63.0,1,0,13502,77.9583,D7,S
280,281,0,3,"Duane, Mr. Frank",male,65.0,0,0,336439,7.7500,NaN,Q
326,327,0,3,"Nysveen, Mr. Johan Hansen",male,61.0,0,0,345364,6.2375,NaN,S
438,439,0,1,"Fortune, Mr. Mark",male,64.0,1,4,19950,263.0000,C23 C25 C27,S
456,457,0,1,"Millet, Mr. Francis Davis",male,65.0,0,0,13509,26.5500,E38,S
483,484,1,3,"Turkula, Mrs. (Hedwig)",female,63.0,0,0,4134,9.5875,NaN,S
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C
545,546,0,1,"Nicholson, Mr. Arthur Ernest",male,64.0,0,0,693,26.0000,NaN,S
555,556,0,1,"Wright, Mr. George",male,62.0,0,0,113807,26.5500,NaN,S
570,571,1,2,"Harris, Mr. George",male,62.0,0,0,S.W./PP 752,10.5000,NaN,S
625,626,0,1,"Sutton, Mr. Frederick",male,61.0,0,0,36963,32.3208,D50,S
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S
672,673,0,2,"Mitchell, Mr. Henry Michael",male,70.0,0,0,C.A. 24580,10.5000,NaN,S
745,746,0,1,"Crosby, Capt. Edward Gifford",male,70.0,1,1,WE/P 5735,71.0000,B22,S
829,830,1,1,"Stone, Mrs. George Nelson (Martha Evelyn)",female,62.0,0,0,113572,80.0000,B28,NaN
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S

In [17]:
df[(df["Fare"] > 100) & (df["Pclass"] == 1)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.00,3,2,19950,263.0000,C23 C25 C27,S
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C
88,89,1,1,"Fortune, Miss Mabel Helen",female,23.00,3,2,19950,263.0000,C23 C25 C27,S
118,119,0,1,"Baxter, Mr. Quigg Edmond",male,24.00,0,1,PC 17558,247.5208,B58 B60,C
195,196,1,1,"Lurette, Miss Elise",female,58.00,0,0,PC 17569,146.5208,B80,C
215,216,1,1,"Newell, Miss Madeleine",female,31.00,1,0,35273,113.2750,D36,C
258,259,1,1,"Ward, Miss Anna",female,35.00,0,0,PC 17755,512.3292,NaN,C
268,269,1,1,"Graham, Mrs. William Thompson (Edith Junkins)",female,58.00,0,1,PC 17582,153.4625,C125,S
269,270,1,1,"Bissette, Miss Amelia",female,35.00,0,0,PC 17760,135.6333,C99,S
297,298,0,1,"Allison, Miss Helen Loraine",female,2.00,1,2,113781,151.5500,C22 C26,S
299,300,1,1,"Baxter, Mrs. James (Helene DeLaudeniere Chaput)",female,50.00,0,1,PC 17558,247.5208,B58 B60,C
305,306,1,1,"Allison, Master Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S
306,307,1,1,"Fleming, Miss Margaret",female,NaN,0,0,17421,110.8833,NaN,C
307,308,1,1,"Penasco y Castellana, Mrs. Victor de Satode (M...",female,17.00,1,0,PC 17758,108.9000,C65,C
311,312,1,1,"Ryerson, Miss Emily Borie",female,18.00,2,2,PC 17608,262.3750,B57 B59 B63 B66,C
318,319,1,1,"Wick, Miss Mary Natalie",female,31.00,0,2,36928,164.8667,C7,S
319,320,1,1,"Spedden, Mrs. Frederic Oakley (Margaretta Corn...",female,40.00,1,1,16966,134.5000,E34,C
325,326,1,1,"Young, Miss Marie Grice",female,36.00,0,0,PC 17760,135.6333,C32,C
332,333,0,1,"Graham, Mr. George Edward",male,38.00,0,1,PC 17582,153.4625,C91,S
334,335,1,1,"Frauenthal, Mrs. Henry William (Clara Heinshei...",female,NaN,1,0,PC 17611,133.6500,NaN,S
337,338,1,1,"Burns, Miss Elizabeth Margaret",female,41.00,0,0,16966,134.5000,E40,C
341,342,1,1,"Fortune, Miss Alice Elizabeth",female,24.00,3,2,19950,263.0000,C23 C25 C27,S
373,374,0,1,"Ringhini, Mr. Sante",male,22.00,0,0,PC 17760,135.6333,NaN,C
377,378,0,1,"Widener, Mr. Harry Elkins",male,27.00,0,2,113503,211.5000,C82,C
380,381,1,1,"Bidois, Miss Rosalie",female,42.00,0,0,PC 17757,227.5250,NaN,C
390,391,1,1,"Carter, Mr. William Ernest",male,36.00,1,2,113760,120.0000,B96 B98,S
393,394,1,1,"Newell, Miss Marjorie",female,23.00,1,0,35273,113.2750,D36,C
435,436,1,1,"Carter, Miss Lucile Polk",female,14.00,1,2,113760,120.0000,B96 B98,S
438,439,0,1,"Fortune, Mr. Mark",male,64.00,1,4,19950,263.0000,C23 C25 C27,S
498,499,0,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.00,1,2,113781,151.5500,C22 C26,S
505,506,0,1,"Penasco y Castellana, Mr. Victor de Satode",male,18.00,1,0,PC 17758,108.9000,C65,C
527,528,0,1,"Farthing, Mr. John",male,NaN,0,0,PC 17483,221.7792,C95,S
537,538,1,1,"LeRoy, Miss Bertha",female,30.00,0,0,PC 17761,106.4250,NaN,C
544,545,0,1,"Douglas, Mr. Walter Donald",male,50.00,1,0,PC 17761,106.4250,C86,C
550,551,1,1,"Thayer, Mr. John Borland Jr",male,17.00,0,2,17421,110.8833,C70,C
557,558,0,1,"Robbins, Mr. Victor",male,NaN,0,0,PC 17757,227.5250,NaN,C
581,582,1,1,"Thayer, Mrs. John Borland (Marian Longstreth M...",female,39.00,1,1,17421,110.8833,C68,C
609,610,1,1,"Shutes, Miss Elizabeth W",female,40.00,0,0,PC 17582,153.4625,C125,S
659,660,0,1,"Newell, Mr. Arthur Webster",male,58.00,0,2,35273,113.2750,D48,C
660,661,1,1,"Frauenthal, Dr. Henry William",male,50.00,2,0,PC 17611,133.6500,NaN,S
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.00,0,1,PC 17755,512.3292,B51 B53 B55,C
689,690,1,1,"Madill, Miss Georgette Alexandra",female,15.00,0,1,24160,211.3375,B5,S
698,699,0,1,"Thayer, Mr. John Borland",male,49.00,1,1,17421,110.8833,C68,C
700,701,1,1,"Astor, Mrs. John Jacob (Madeleine Talmadge Force)",female,18.00,1,0,PC 17757,227.5250,C62 C64,C
708,709,1,1,"Cleaver, Miss Alice",female,22.00,0,0,113781,151.5500,NaN,S
716,717,1,1,"Endres, Miss Caroline Louise",female,38.00,0,0,PC 17757,227.5250,C45,C
730,731,1,1,"Allen, Miss Elisabeth Walton",female,29.00,0,0,24160,211.3375,B5,S
737,738,1,1,"Lesurer, Mr. Gustave J",male,35.00,0,0,PC 17755,512.3292,B101,C
742,743,1,1,"Ryerson, Miss Susan Parker ""Suzette""",female,21.00,2,2,PC 17608,262.3750,B57 B59 B63 B66,C
763,764,1,1,"Carter, Mrs. William Ernest (Lucile Polk)",female,36.00,1,2,113760,120.0000,B96 B98,S
779,780,1,1,"Robert, Mrs. Edward Scott (Elisabeth Walton Mc...",female,43.00,0,1,24160,211.3375,B3,S
802,803,1,1,"Carter, Master William Thornton II",male,11.00,1,2,113760,120.0000,B96 B98,S
856,857,1,1,"Wick, Mrs. George Dennick (Mary Hitchcock)",female,45.00,1,1,36928,164.8667,NaN,S

In [18]:
df[df["Age"].isna()]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C
26,27,0,3,"Emir, Mr. Farred Chehab",male,NaN,0,0,2631,7.2250,NaN,C
28,29,1,3,"O'Dwyer, Miss Ellen ""Nellie""",female,NaN,0,0,330959,7.8792,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...,...
859,860,0,3,"Razi, Mr. Raihed",male,NaN,0,0,2629,7.2292,NaN,C
863,864,0,3,"Sage, Miss Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S
868,869,0,3,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,9.5000,NaN,S
878,879,0,3,"Laleff, Mr. Kristo",male,NaN,0,0,349217,7.8958,NaN,S
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S

Explanation:

Filtering is used to display rows that match specific conditions.

isna() is used to identify missing values in the Age column.

In [19]:
df[::-1]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S

In [20]:
df.drop(columns=["Cabin"])

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,S
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q

In [21]:
df.dropna(subset=["Age"])

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

Explanation:

drop() is used to remove columns.

dropna() removes rows that contain missing values in the selected column.

In [22]:
df["Fare_Euro"] = df["Fare"] * 0.92

df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare_Euro
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,6.670000
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,65.580636
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,7.291000
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,48.852000
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,7.406000

In [23]:
average_age = df["Age"].mean()

df["Age_Difference"] = df["Age"] - average_age

df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare_Euro,Age_Difference
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,6.670000,-7.699118
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,65.580636,8.300882
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,7.291000,-3.699118
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,48.852000,5.300882
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,7.406000,5.300882

In [24]:
custom_array = np.array([1, 2])

df[["Age", "Fare"]] - custom_array

      Age     Fare
0    21.0   5.2500
1    37.0  69.2833
2    25.0   5.9250
3    34.0  51.1000
4    34.0   6.0500
..    ...      ...
886  26.0  11.0000
887  18.0  28.0000
888   NaN  21.4500
889  25.0  28.0000
890  31.0   5.7500

[891 rows x 2 columns]

Explanation:

A new column is created by multiplying Fare values by the Euro conversion rate.

mean() calculates the average age.

NumPy arrays can be used in arithmetic operations with DataFrame columns.

In [25]:
df["Name_Length"] = df["Name"].apply(len)

df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare_Euro,Age_Difference,Name_Length
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,6.670000,-7.699118,23
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,65.580636,8.300882,51
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,7.291000,-3.699118,21
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,48.852000,5.300882,44
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,7.406000,5.300882,24

In [26]:
df["Fare_Age_Diff"] = df["Fare"] - df["Age"]

df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare_Euro,Age_Difference,Name_Length,Fare_Age_Diff
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,6.670000,-7.699118,23,-14.7500
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,65.580636,8.300882,51,33.2833
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,7.291000,-3.699118,21,-18.0750
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,48.852000,5.300882,44,18.1000
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,7.406000,5.300882,24,-26.9500

In [27]:
df.round(1)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare_Euro,Age_Difference,Name_Length,Fare_Age_Diff
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2,NaN,S,6.7,-7.7,23,-14.8
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.3,C85,C,65.6,8.3,51,33.3
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9,NaN,S,7.3,-3.7,21,-18.1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1,C123,S,48.9,5.3,44,18.1
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0,NaN,S,7.4,5.3,24,-27.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0,NaN,S,12.0,-2.7,21,-14.0
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0,B42,S,27.6,-10.7,27,11.0
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4,NaN,S,21.6,NaN,39,NaN
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0,C148,C,27.6,-3.7,21,4.0
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.8,NaN,Q,7.1,2.3,19,-24.2

Explanation:

apply(len) counts the number of characters in each passenger name.

round(1) rounds all numerical values to one decimal place.

In [28]:
df["Sex_Code"] = df["Sex"].map({
    "male": 0,
    "female": 1
})

df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare_Euro,Age_Difference,Name_Length,Fare_Age_Diff,Sex_Code
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,6.670000,-7.699118,23,-14.7500,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,65.580636,8.300882,51,33.2833,1
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,7.291000,-3.699118,21,-18.0750,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,48.852000,5.300882,44,18.1000,1
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,7.406000,5.300882,24,-26.9500,0

In [29]:
def age_group(age):
    if pd.isna(age):
        return "unknown"
    elif age < 18:
        return "child"
    elif age < 60:
        return "adult"
    else:
        return "senior"

In [30]:
df["Age_Group"] = df["Age"].apply(age_group)

df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare_Euro,Age_Difference,Name_Length,Fare_Age_Diff,Sex_Code,Age_Group
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,6.670000,-7.699118,23,-14.7500,0,adult
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,65.580636,8.300882,51,33.2833,1,adult
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,7.291000,-3.699118,21,-18.0750,1,adult
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,48.852000,5.300882,44,18.1000,1,adult
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,7.406000,5.300882,24,-26.9500,0,adult

Explanation:

map() converts categorical values into numeric codes.

apply() is used to apply the custom age_group function to every Age value.

In [31]:
import csv
import time

In [32]:
# Pandas version
start = time.time()

pandas_single_row = df.iloc[0]

end = time.time()
pandas_time = end - start

print(pandas_single_row)
print("Pandas time:", pandas_time)

PassengerId                             1
Survived                                0
Pclass                                  3
Name              Braund, Mr. Owen Harris
Sex                                  male
Age                                  22.0
SibSp                                   1
Parch                                   0
Ticket                          A/5 21171
Fare                                 7.25
Cabin                                 NaN
Embarked                                S
Fare_Euro                            6.67
Age_Difference                  -7.699118
Name_Length                            23
Fare_Age_Diff                      -14.75
Sex_Code                                0
Age_Group                           adult
Name: 0, dtype: object
Pandas time: 0.0

In [33]:
# Pure Python version
start = time.time()

data_list = df.to_dict("records")
python_single_row = data_list[0]

end = time.time()
python_time = end - start

print(python_single_row)
print("Pure Python time:", python_time)

{'PassengerId': 1, 'Survived': 0, 'Pclass': 3, 'Name': 'Braund, Mr. Owen Harris', 'Sex': 'male', 'Age': 22.0, 'SibSp': 1, 'Parch': 0, 'Ticket': 'A/5 21171', 'Fare': 7.25, 'Cabin': nan, 'Embarked': 'S', 'Fare_Euro': 6.67, 'Age_Difference': -7.69911764705882, 'Name_Length': 23, 'Fare_Age_Diff': -14.75, 'Sex_Code': 0, 'Age_Group': 'adult'}
Pure Python time: 0.014487028121948242

Task2

In [34]:
# Pandas version
start = time.time()

pandas_age_above_60 = df[df["Age"] > 60]

end = time.time()
pandas_time = end - start

print(pandas_age_above_60)
print("Pandas time:", pandas_time)

     PassengerId  Survived  Pclass                                       Name  \
33            34         0       2                      Wheadon, Mr. Edward H
54            55         0       1             Ostby, Mr. Engelhart Cornelius
96            97         0       1                  Goldschmidt, Mr. George B
116          117         0       3                       Connors, Mr. Patrick
170          171         0       1                  Van der hoef, Mr. Wyckoff
252          253         0       1                  Stead, Mr. William Thomas
275          276         1       1           Andrews, Miss Kornelia Theodosia
280          281         0       3                           Duane, Mr. Frank
326          327         0       3                  Nysveen, Mr. Johan Hansen
438          439         0       1                          Fortune, Mr. Mark
456          457         0       1                  Millet, Mr. Francis Davis
483          484         1       3                     Turkula, Mrs. (Hedwig)
493          494         0       1                    Artagaveytia, Mr. Ramon
545          546         0       1               Nicholson, Mr. Arthur Ernest
555          556         0       1                         Wright, Mr. George
570          571         1       2                         Harris, Mr. George
625          626         0       1                      Sutton, Mr. Frederick
630          631         1       1       Barkworth, Mr. Algernon Henry Wilson
672          673         0       2                Mitchell, Mr. Henry Michael
745          746         0       1               Crosby, Capt. Edward Gifford
829          830         1       1  Stone, Mrs. George Nelson (Martha Evelyn)
851          852         0       3                        Svensson, Mr. Johan

        Sex   Age  SibSp  Parch       Ticket      Fare        Cabin Embarked  \
33     male  66.0      0      0   C.A. 24579   10.5000          NaN        S
54     male  65.0      0      1       113509   61.9792          B30        C
96     male  71.0      0      0     PC 17754   34.6542           A5        C
116    male  70.5      0      0       370369    7.7500          NaN        Q
170    male  61.0      0      0       111240   33.5000          B19        S
252    male  62.0      0      0       113514   26.5500          C87        S
275  female  63.0      1      0        13502   77.9583           D7        S
280    male  65.0      0      0       336439    7.7500          NaN        Q
326    male  61.0      0      0       345364    6.2375          NaN        S
438    male  64.0      1      4        19950  263.0000  C23 C25 C27        S
456    male  65.0      0      0        13509   26.5500          E38        S
483  female  63.0      0      0         4134    9.5875          NaN        S
493    male  71.0      0      0     PC 17609   49.5042          NaN        C
545    male  64.0      0      0          693   26.0000          NaN        S
555    male  62.0      0      0       113807   26.5500          NaN        S
570    male  62.0      0      0  S.W./PP 752   10.5000          NaN        S
625    male  61.0      0      0        36963   32.3208          D50        S
630    male  80.0      0      0        27042   30.0000          A23        S
672    male  70.0      0      0   C.A. 24580   10.5000          NaN        S
745    male  70.0      1      1    WE/P 5735   71.0000          B22        S
829  female  62.0      0      0       113572   80.0000          B28      NaN
851    male  74.0      0      0       347060    7.7750          NaN        S

      Fare_Euro  Age_Difference  Name_Length  Fare_Age_Diff  Sex_Code  \
33     9.660000       36.300882           21       -55.5000         0
54    57.020864       35.300882           30        -3.0208         0
96    31.881864       41.300882           25       -36.3458         0
116    7.130000       40.800882           20       -62.7500         0
170   30.820000       31.300882           25       -27.5000         0
252   24.426000       32.300882           25       -35.4500         0
275   71.721636       33.300882           32        14.9583         1
280    7.130000       35.300882           16       -57.2500         0
326    5.738500       31.300882           25       -54.7625         0
438  241.960000       34.300882           17       199.0000         0
456   24.426000       35.300882           25       -38.4500         0
483    8.820500       33.300882           22       -53.4125         1
493   45.543864       41.300882           23       -21.4958         0
545   23.920000       34.300882           28       -38.0000         0
555   24.426000       32.300882           18       -35.4500         0
570    9.660000       32.300882           18       -51.5000         0
625   29.735136       31.300882           21       -28.6792         0
630   27.600000       50.300882           36       -50.0000         0
672    9.660000       40.300882           27       -59.5000         0
745   65.320000       40.300882           28         1.0000         0
829   73.600000       32.300882           41        18.0000         1
851    7.153000       44.300882           19       -66.2250         0

    Age_Group
33     senior
54     senior
96     senior
116    senior
170    senior
252    senior
275    senior
280    senior
326    senior
438    senior
456    senior
483    senior
493    senior
545    senior
555    senior
570    senior
625    senior
630    senior
672    senior
745    senior
829    senior
851    senior
Pandas time: 0.011585474014282227

In [35]:
# Pure Python version
start = time.time()

data_list = df.to_dict("records")

python_age_above_60 = []

for row in data_list:
    if row["Age"] > 60:
        python_age_above_60.append(row)

end = time.time()
python_time = end - start

print(python_age_above_60)
print("Pure Python time:", python_time)

[{'PassengerId': 34, 'Survived': 0, 'Pclass': 2, 'Name': 'Wheadon, Mr. Edward H', 'Sex': 'male', 'Age': 66.0, 'SibSp': 0, 'Parch': 0, 'Ticket': 'C.A. 24579', 'Fare': 10.5, 'Cabin': nan, 'Embarked': 'S', 'Fare_Euro': 9.66, 'Age_Difference': 36.30088235294118, 'Name_Length': 21, 'Fare_Age_Diff': -55.5, 'Sex_Code': 0, 'Age_Group': 'senior'}, {'PassengerId': 55, 'Survived': 0, 'Pclass': 1, 'Name': 'Ostby, Mr. Engelhart Cornelius', 'Sex': 'male', 'Age': 65.0, 'SibSp': 0, 'Parch': 1, 'Ticket': '113509', 'Fare': 61.9792, 'Cabin': 'B30', 'Embarked': 'C', 'Fare_Euro': 57.020864, 'Age_Difference': 35.30088235294118, 'Name_Length': 30, 'Fare_Age_Diff': -3.0208000000000013, 'Sex_Code': 0, 'Age_Group': 'senior'}, {'PassengerId': 97, 'Survived': 0, 'Pclass': 1, 'Name': 'Goldschmidt, Mr. George B', 'Sex': 'male', 'Age': 71.0, 'SibSp': 0, 'Parch': 0, 'Ticket': 'PC 17754', 'Fare': 34.6542, 'Cabin': 'A5', 'Embarked': 'C', 'Fare_Euro': 31.881864000000004, 'Age_Difference': 41.30088235294118, 'Name_Length': 25, 'Fare_Age_Diff': -36.3458, 'Sex_Code': 0, 'Age_Group': 'senior'}, {'PassengerId': 117, 'Survived': 0, 'Pclass': 3, 'Name': 'Connors, Mr. Patrick', 'Sex': 'male', 'Age': 70.5, 'SibSp': 0, 'Parch': 0, 'Ticket': '370369', 'Fare': 7.75, 'Cabin': nan, 'Embarked': 'Q', 'Fare_Euro': 7.13, 'Age_Difference': 40.80088235294118, 'Name_Length': 20, 'Fare_Age_Diff': -62.75, 'Sex_Code': 0, 'Age_Group': 'senior'}, {'PassengerId': 171, 'Survived': 0, 'Pclass': 1, 'Name': 'Van der hoef, Mr. Wyckoff', 'Sex': 'male', 'Age': 61.0, 'SibSp': 0, 'Parch': 0, 'Ticket': '111240', 'Fare': 33.5, 'Cabin': 'B19', 'Embarked': 'S', 'Fare_Euro': 30.82, 'Age_Difference': 31.30088235294118, 'Name_Length': 25, 'Fare_Age_Diff': -27.5, 'Sex_Code': 0, 'Age_Group': 'senior'}, {'PassengerId': 253, 'Survived': 0, 'Pclass': 1, 'Name': 'Stead, Mr. William Thomas', 'Sex': 'male', 'Age': 62.0, 'SibSp': 0, 'Parch': 0, 'Ticket': '113514', 'Fare': 26.55, 'Cabin': 'C87', 'Embarked': 'S', 'Fare_Euro': 24.426000000000002, 'Age_Difference': 32.30088235294118, 'Name_Length': 25, 'Fare_Age_Diff': -35.45, 'Sex_Code': 0, 'Age_Group': 'senior'}, {'PassengerId': 276, 'Survived': 1, 'Pclass': 1, 'Name': 'Andrews, Miss Kornelia Theodosia', 'Sex': 'female', 'Age': 63.0, 'SibSp': 1, 'Parch': 0, 'Ticket': '13502', 'Fare': 77.9583, 'Cabin': 'D7', 'Embarked': 'S', 'Fare_Euro': 71.721636, 'Age_Difference': 33.30088235294118, 'Name_Length': 32, 'Fare_Age_Diff': 14.958299999999994, 'Sex_Code': 1, 'Age_Group': 'senior'}, {'PassengerId': 281, 'Survived': 0, 'Pclass': 3, 'Name': 'Duane, Mr. Frank', 'Sex': 'male', 'Age': 65.0, 'SibSp': 0, 'Parch': 0, 'Ticket': '336439', 'Fare': 7.75, 'Cabin': nan, 'Embarked': 'Q', 'Fare_Euro': 7.13, 'Age_Difference': 35.30088235294118, 'Name_Length': 16, 'Fare_Age_Diff': -57.25, 'Sex_Code': 0, 'Age_Group': 'senior'}, {'PassengerId': 327, 'Survived': 0, 'Pclass': 3, 'Name': 'Nysveen, Mr. Johan Hansen', 'Sex': 'male', 'Age': 61.0, 'SibSp': 0, 'Parch': 0, 'Ticket': '345364', 'Fare': 6.2375, 'Cabin': nan, 'Embarked': 'S', 'Fare_Euro': 5.7385, 'Age_Difference': 31.30088235294118, 'Name_Length': 25, 'Fare_Age_Diff': -54.7625, 'Sex_Code': 0, 'Age_Group': 'senior'}, {'PassengerId': 439, 'Survived': 0, 'Pclass': 1, 'Name': 'Fortune, Mr. Mark', 'Sex': 'male', 'Age': 64.0, 'SibSp': 1, 'Parch': 4, 'Ticket': '19950', 'Fare': 263.0, 'Cabin': 'C23 C25 C27', 'Embarked': 'S', 'Fare_Euro': 241.96, 'Age_Difference': 34.30088235294118, 'Name_Length': 17, 'Fare_Age_Diff': 199.0, 'Sex_Code': 0, 'Age_Group': 'senior'}, {'PassengerId': 457, 'Survived': 0, 'Pclass': 1, 'Name': 'Millet, Mr. Francis Davis', 'Sex': 'male', 'Age': 65.0, 'SibSp': 0, 'Parch': 0, 'Ticket': '13509', 'Fare': 26.55, 'Cabin': 'E38', 'Embarked': 'S', 'Fare_Euro': 24.426000000000002, 'Age_Difference': 35.30088235294118, 'Name_Length': 25, 'Fare_Age_Diff': -38.45, 'Sex_Code': 0, 'Age_Group': 'senior'}, {'PassengerId': 484, 'Survived': 1, 'Pclass': 3, 'Name': 'Turkula, Mrs. (Hedwig)', 'Sex': 'female', 'Age': 63.0, 'SibSp': 0, 'Parch': 0, 'Ticket': '4134', 'Fare': 9.5875, 'Cabin': nan, 'Embarked': 'S', 'Fare_Euro': 8.820500000000001, 'Age_Difference': 33.30088235294118, 'Name_Length': 22, 'Fare_Age_Diff': -53.4125, 'Sex_Code': 1, 'Age_Group': 'senior'}, {'PassengerId': 494, 'Survived': 0, 'Pclass': 1, 'Name': 'Artagaveytia, Mr. Ramon', 'Sex': 'male', 'Age': 71.0, 'SibSp': 0, 'Parch': 0, 'Ticket': 'PC 17609', 'Fare': 49.5042, 'Cabin': nan, 'Embarked': 'C', 'Fare_Euro': 45.543864, 'Age_Difference': 41.30088235294118, 'Name_Length': 23, 'Fare_Age_Diff': -21.495800000000003, 'Sex_Code': 0, 'Age_Group': 'senior'}, {'PassengerId': 546, 'Survived': 0, 'Pclass': 1, 'Name': 'Nicholson, Mr. Arthur Ernest', 'Sex': 'male', 'Age': 64.0, 'SibSp': 0, 'Parch': 0, 'Ticket': '693', 'Fare': 26.0, 'Cabin': nan, 'Embarked': 'S', 'Fare_Euro': 23.92, 'Age_Difference': 34.30088235294118, 'Name_Length': 28, 'Fare_Age_Diff': -38.0, 'Sex_Code': 0, 'Age_Group': 'senior'}, {'PassengerId': 556, 'Survived': 0, 'Pclass': 1, 'Name': 'Wright, Mr. George', 'Sex': 'male', 'Age': 62.0, 'SibSp': 0, 'Parch': 0, 'Ticket': '113807', 'Fare': 26.55, 'Cabin': nan, 'Embarked': 'S', 'Fare_Euro': 24.426000000000002, 'Age_Difference': 32.30088235294118, 'Name_Length': 18, 'Fare_Age_Diff': -35.45, 'Sex_Code': 0, 'Age_Group': 'senior'}, {'PassengerId': 571, 'Survived': 1, 'Pclass': 2, 'Name': 'Harris, Mr. George', 'Sex': 'male', 'Age': 62.0, 'SibSp': 0, 'Parch': 0, 'Ticket': 'S.W./PP 752', 'Fare': 10.5, 'Cabin': nan, 'Embarked': 'S', 'Fare_Euro': 9.66, 'Age_Difference': 32.30088235294118, 'Name_Length': 18, 'Fare_Age_Diff': -51.5, 'Sex_Code': 0, 'Age_Group': 'senior'}, {'PassengerId': 626, 'Survived': 0, 'Pclass': 1, 'Name': 'Sutton, Mr. Frederick', 'Sex': 'male', 'Age': 61.0, 'SibSp': 0, 'Parch': 0, 'Ticket': '36963', 'Fare': 32.3208, 'Cabin': 'D50', 'Embarked': 'S', 'Fare_Euro': 29.735136, 'Age_Difference': 31.30088235294118, 'Name_Length': 21, 'Fare_Age_Diff': -28.6792, 'Sex_Code': 0, 'Age_Group': 'senior'}, {'PassengerId': 631, 'Survived': 1, 'Pclass': 1, 'Name': 'Barkworth, Mr. Algernon Henry Wilson', 'Sex': 'male', 'Age': 80.0, 'SibSp': 0, 'Parch': 0, 'Ticket': '27042', 'Fare': 30.0, 'Cabin': 'A23', 'Embarked': 'S', 'Fare_Euro': 27.6, 'Age_Difference': 50.30088235294118, 'Name_Length': 36, 'Fare_Age_Diff': -50.0, 'Sex_Code': 0, 'Age_Group': 'senior'}, {'PassengerId': 673, 'Survived': 0, 'Pclass': 2, 'Name': 'Mitchell, Mr. Henry Michael', 'Sex': 'male', 'Age': 70.0, 'SibSp': 0, 'Parch': 0, 'Ticket': 'C.A. 24580', 'Fare': 10.5, 'Cabin': nan, 'Embarked': 'S', 'Fare_Euro': 9.66, 'Age_Difference': 40.30088235294118, 'Name_Length': 27, 'Fare_Age_Diff': -59.5, 'Sex_Code': 0, 'Age_Group': 'senior'}, {'PassengerId': 746, 'Survived': 0, 'Pclass': 1, 'Name': 'Crosby, Capt. Edward Gifford', 'Sex': 'male', 'Age': 70.0, 'SibSp': 1, 'Parch': 1, 'Ticket': 'WE/P 5735', 'Fare': 71.0, 'Cabin': 'B22', 'Embarked': 'S', 'Fare_Euro': 65.32000000000001, 'Age_Difference': 40.30088235294118, 'Name_Length': 28, 'Fare_Age_Diff': 1.0, 'Sex_Code': 0, 'Age_Group': 'senior'}, {'PassengerId': 830, 'Survived': 1, 'Pclass': 1, 'Name': 'Stone, Mrs. George Nelson (Martha Evelyn)', 'Sex': 'female', 'Age': 62.0, 'SibSp': 0, 'Parch': 0, 'Ticket': '113572', 'Fare': 80.0, 'Cabin': 'B28', 'Embarked': nan, 'Fare_Euro': 73.60000000000001, 'Age_Difference': 32.30088235294118, 'Name_Length': 41, 'Fare_Age_Diff': 18.0, 'Sex_Code': 1, 'Age_Group': 'senior'}, {'PassengerId': 852, 'Survived': 0, 'Pclass': 3, 'Name': 'Svensson, Mr. Johan', 'Sex': 'male', 'Age': 74.0, 'SibSp': 0, 'Parch': 0, 'Ticket': '347060', 'Fare': 7.775, 'Cabin': nan, 'Embarked': 'S', 'Fare_Euro': 7.1530000000000005, 'Age_Difference': 44.30088235294118, 'Name_Length': 19, 'Fare_Age_Diff': -66.225, 'Sex_Code': 0, 'Age_Group': 'senior'}]
Pure Python time: 0.005655527114868164

Task3

In [36]:
# Pandas version
start = time.time()

df["Fare_Euro_Pandas"] = df["Fare"] * 0.92

end = time.time()
pandas_time = end - start

print(df[["Fare", "Fare_Euro_Pandas"]].head())
print("Pandas time:", pandas_time)

      Fare  Fare_Euro_Pandas
0   7.2500          6.670000
1  71.2833         65.580636
2   7.9250          7.291000
3  53.1000         48.852000
4   8.0500          7.406000
Pandas time: 0.00113677978515625

In [37]:
# Pure Python version
start = time.time()

data_list = df.to_dict("records")

for row in data_list:
    row["Fare_Euro_Python"] = row["Fare"] * 0.92

end = time.time()
python_time = end - start

print(data_list[:5])
print("Pure Python time:", python_time)

[{'PassengerId': 1, 'Survived': 0, 'Pclass': 3, 'Name': 'Braund, Mr. Owen Harris', 'Sex': 'male', 'Age': 22.0, 'SibSp': 1, 'Parch': 0, 'Ticket': 'A/5 21171', 'Fare': 7.25, 'Cabin': nan, 'Embarked': 'S', 'Fare_Euro': 6.67, 'Age_Difference': -7.69911764705882, 'Name_Length': 23, 'Fare_Age_Diff': -14.75, 'Sex_Code': 0, 'Age_Group': 'adult', 'Fare_Euro_Pandas': 6.67, 'Fare_Euro_Python': 6.67}, {'PassengerId': 2, 'Survived': 1, 'Pclass': 1, 'Name': 'Cumings, Mrs. John Bradley (Florence Briggs Thayer)', 'Sex': 'female', 'Age': 38.0, 'SibSp': 1, 'Parch': 0, 'Ticket': 'PC 17599', 'Fare': 71.2833, 'Cabin': 'C85', 'Embarked': 'C', 'Fare_Euro': 65.580636, 'Age_Difference': 8.30088235294118, 'Name_Length': 51, 'Fare_Age_Diff': 33.2833, 'Sex_Code': 1, 'Age_Group': 'adult', 'Fare_Euro_Pandas': 65.580636, 'Fare_Euro_Python': 65.580636}, {'PassengerId': 3, 'Survived': 1, 'Pclass': 3, 'Name': 'Heikkinen, Miss Laina', 'Sex': 'female', 'Age': 26.0, 'SibSp': 0, 'Parch': 0, 'Ticket': 'STON/O2. 3101282', 'Fare': 7.925, 'Cabin': nan, 'Embarked': 'S', 'Fare_Euro': 7.291, 'Age_Difference': -3.69911764705882, 'Name_Length': 21, 'Fare_Age_Diff': -18.075, 'Sex_Code': 1, 'Age_Group': 'adult', 'Fare_Euro_Pandas': 7.291, 'Fare_Euro_Python': 7.291}, {'PassengerId': 4, 'Survived': 1, 'Pclass': 1, 'Name': 'Futrelle, Mrs. Jacques Heath (Lily May Peel)', 'Sex': 'female', 'Age': 35.0, 'SibSp': 1, 'Parch': 0, 'Ticket': '113803', 'Fare': 53.1, 'Cabin': 'C123', 'Embarked': 'S', 'Fare_Euro': 48.852000000000004, 'Age_Difference': 5.30088235294118, 'Name_Length': 44, 'Fare_Age_Diff': 18.1, 'Sex_Code': 1, 'Age_Group': 'adult', 'Fare_Euro_Pandas': 48.852000000000004, 'Fare_Euro_Python': 48.852000000000004}, {'PassengerId': 5, 'Survived': 0, 'Pclass': 3, 'Name': 'Allen, Mr. William Henry', 'Sex': 'male', 'Age': 35.0, 'SibSp': 0, 'Parch': 0, 'Ticket': '373450', 'Fare': 8.05, 'Cabin': nan, 'Embarked': 'S', 'Fare_Euro': 7.406000000000001, 'Age_Difference': 5.30088235294118, 'Name_Length': 24, 'Fare_Age_Diff': -26.95, 'Sex_Code': 0, 'Age_Group': 'adult', 'Fare_Euro_Pandas': 7.406000000000001, 'Fare_Euro_Python': 7.406000000000001}]
Pure Python time: 0.01017904281616211

Explanation:

For Part 8, I selected one task from Part 2, Part 3, and Part 5.

The Pandas version uses DataFrame operations.

The pure Python version first converts the dataset into a list of dictionaries, then uses indexing and loops to complete the same tasks.

The execution time is measured with the time module to compare both methods.